### ISSUE TITLE
Links to Papers in Readme Are Incorrect

### ISSUE THREAD

**Issue by adam-hartshorne** [imbirik/LieStationaryKernels#1]
The links to Part I / Part II of the paper in the readme don't resolve to the correct locations.

**Comment by aterenin** [comment]
That's because you found this repo before we had the change to update or even announce or work.. 🙂 

Part I landed on arXiv today: https://arxiv.org/abs/2208.14960. We're in process of finishing writing up part II - please give us a few months.

**Comment by imbirik** [comment]
Thank you, @adam-hartshorne. I've updated the first link.
