### ISSUE TITLE
Question for the parametrization

### ISSUE THREAD

**Issue by Fangwq** [imbirik/LieStationaryKernels#4]
Thank you for the clarification for question #3. However, I still feel confused. Why this is the right way? What's the difference between this paper and **Matern Gaussian processes on Riemannian manifolds**(just the `continuous` and `discrete` way)? In the file `torus.py`(in the package `GeometricKernels`), the parametrization is as follows:
```
x = B.linspace(0, 2*3.14159, 101)
xx = np.meshgrid(x,x)
X = B.stack(*xx, axis=-1).reshape((-1, 2))
```
Would you like to point out where do I misunderstand? Or, the codes in the `LieStationaryKernels` already have `2\pi` in function `chi(self, x)` makes them different? Thank you very much!

**Comment by imbirik** [comment]
Yes, you are right. The only difference is `2\pi` multiplication at `TorusCharacter`.  There are two equivalent ways to parameterize torus as `[0,1]^n` and `[0,2\pi]^n`. In the latter case characters  `e^i<v,x>` are used. In case `[0,1]^n` we should use `e^2\pi*i<v,x>`.

**Comment by Fangwq** [comment]
Thank you for your clarification.
